#############################################################
#
# Ref to the ARTICLE
# 
#  Code to generate the Phyloseq objects and DESeq objects used in the manuscript
#  d.bulgarelli@dundee.ac.uk 
#  Revision 08/20
#
#############################################################

#############################################################
# Clean-up the memory and start a new session
#############################################################

rm(list=ls())
dev.off()

#############################################################
# Libraries required
#############################################################

#required packages 
library("phyloseq")
library("DESeq2")
library ("ape")
library ("vegan")

#retrieve R and package versions and compare to the uploaded file in gtHub for the reproducibility of the code
sessionInfo()

#DAVIDE_DUNDEE
setwd("/cluster/db/R_shared/NT2020_R_data/")


#############################################################
#import the DADA2 phyloseq object generated by James Abbot
#############################################################

#JH02_NT
JH02_NT_phloseq_DADA2 <- readRDS("JH02_silva138_dada2.rds")
JH02_NT_phloseq_DADA2 
#JH16
JH16_phloseq_DADA2 <- readRDS("JH16_silva138_dada2.rds")
JH16_phloseq_DADA2

##################################################################
#Pre-processing: remove Chloroplast and Mitochondria but retain NA
#################################################################

#JH02_NT
JH02_no_chlor <-subset_taxa(JH02_NT_phloseq_DADA2, (Order!="Chloroplast") | is.na(Order))
JH02_no_chlor

JH02_NT_phloseq_DADA2_no_plants <-subset_taxa(JH02_no_chlor, (Family!="Mitochondria") | is.na(Family))
JH02_NT_phloseq_DADA2_no_plants

#JH16
JH16_no_chlor <-subset_taxa(JH16_phloseq_DADA2, (Order!="Chloroplast") | is.na(Order))
JH16_no_chlor

JH16_phloseq_DADA2_no_plants <-subset_taxa(JH16_no_chlor, (Family!="Mitochondria") | is.na(Family))
JH16_phloseq_DADA2_no_plants

##################################################################
#Merging phyloseq object
##################################################################

JH02_NT_JH16_phloseq_DADA2_no_plants <- merge_phyloseq(JH02_NT_phloseq_DADA2_no_plants, JH16_phloseq_DADA2_no_plants)
JH02_NT_JH16_phloseq_DADA2_no_plants

#check the efficacy of the merging
#number of Unique ASVs among the two objects
unique_ASVs <- (unique(union(taxa_names(JH02_NT_phloseq_DADA2_no_plants),taxa_names(JH16_phloseq_DADA2_no_plants)))) 
length(unique_ASVs)
#the above number should be identical to the number of taxa retrieved from the merged object

#number of ASVs in common among the two objects
common_ASVs <- (intersect(taxa_names(JH02_NT_phloseq_DADA2_no_plants),taxa_names(JH16_phloseq_DADA2_no_plants))) 
length(common_ASVs)

#proportion of common ASVs
length(common_ASVs)/length(unique_ASVs)

##################################################################
#Prune putative contaminant ASVs
##################################################################

#Import the list of contaminat ASVs from JH06 library
Contaminant_ASVs <- read.delim("JH06_contaminant_ASVs_ids.txt", header = FALSE)

#identify the proportion of putative contaminants in the merged object
JH02_JH16_contaminants <- intersect(taxa_names(JH02_NT_JH16_phloseq_DADA2_no_plants),Contaminant_ASVs)

#########################################################################
# Remove ASVs assigned to NA at phylum level
#########################################################################

JH02_NT_JH16_phloseq_DADA2_no_plants_1 <- subset_taxa(JH02_NT_JH16_phloseq_DADA2_no_plants, Phylum!= "NA")

#########################################################################
# Abundance threshold: 20 reads, set as 2% the minimum number of samples
########################################################################

JH02_NT_JH16_phloseq_DADA2_no_plants_2 = filter_taxa(JH02_NT_JH16_phloseq_DADA2_no_plants_1, function(x) sum(x > 20) > (0.02 *length(x)), TRUE)
JH02_NT_JH16_phloseq_DADA2_no_plants_2 
sort(sample_sums(JH02_NT_JH16_phloseq_DADA2_no_plants_2))

##ratio filtered reads/total reads
ratio <- sum(sample_sums(JH02_NT_JH16_phloseq_DADA2_no_plants_2))/sum(sample_sums(JH02_NT_JH16_phloseq_DADA2_no_plants))*100
ratio

#########################################################################
# Generate a simplified mapping file
########################################################################
#export the original mapping file
#write.table(sample_data(JH02_NT_JH16_phloseq_DADA2_no_plants_2), file="JH02_NT_JH16_original_mapping.txt", sep="\t")

#import the simplified mapping file
JH02_NT_JH16_new_map <- read.delim("JH02_NT_JH16_simplified_mapping_2.txt", row.names = 1)

#and replace the old mapping file
sample_data(JH02_NT_JH16_phloseq_DADA2_no_plants_2) <- JH02_NT_JH16_new_map 
sample_data(JH02_NT_JH16_phloseq_DADA2_no_plants_2)
#Note that this mapping file has 7 columns

#########################################################################
# Aggregate samples at genus level (Note: NArm set to false as Phylum NA ASVs pruned above)
########################################################################

JH02_JH16_data_phyloseq_genus <- tax_glom(JH02_NT_JH16_phloseq_DADA2_no_plants_2, taxrank= "Genus", NArm=FALSE, bad_empty=c(NA, "", " ", "\t"))

#compare the two objects
#ASVs
JH02_NT_JH16_phloseq_DADA2_no_plants_2
sort(sample_sums(JH02_NT_JH16_phloseq_DADA2_no_plants_2))
#Genera
JH02_JH16_data_phyloseq_genus
sort(sample_sums(JH02_JH16_data_phyloseq_genus))

####################################################################################
# Rarefy at an even sequencing depth (25,000) and "freeze" these objects for downstream analyses
#####################################################################################

#ASVs : ignore the warnings, the object will be saved right after
#JH02_NT_JH16_rare_25K <- rarefy_even_depth(JH02_NT_JH16_phloseq_DADA2_no_plants_2, 25000)
#saveRDS(JH02_NT_JH16_rare_25K, file ="NT_rare_25K_phyloseq_ASVs_Silva138_0820.rds")

#Genus : ignore the warnings, the object will be saved right after
#JH02_NT_JH16_rare_genus_25K <- rarefy_even_depth(JH02_JH16_data_phyloseq_genus, 25000)
#saveRDS(JH02_NT_JH16_rare_genus_25K, file ="NT_rare_25K_phyloseq_genus_0820_Silva138.rds")

####################################################################################
# End
#####################################################################################

